### ISSUE TITLE
Make member nicknames hyperlinked before sending

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#191]
This will in particular improve UX between Q and Riot, as Riot will make those nice pills out of matrix.to hyperlinks

**Comment by KitsuneRal** [comment]
Note: hyperlinks should only come in `formatted_body`; we intentionally don't send Markdown in plain-text body.

**Comment by krkk** [comment]
I think it'd be better to link user IDs instead of the displayed name
