### ISSUE TITLE
Change/set avatar

### ISSUE THREAD

**Issue by Fxrh** [quotient-im/Quaternion#28]

**Comment by Half-Shot** [comment]
Presumably blocked by #32 since media uploads need to be implemented.

**Comment by Fxrh** [comment]
Both depend on the "upload media", but I wouldn't say that one issue depends on the other

**Comment by KitsuneRal** [comment]
Depends on QMatrixClient/libqmatrixclient#122.

**Comment by KitsuneRal** [comment]
Media uploads and the respective backend method in the lib have landed - it's now a matter of putting it somewhere in the UI.
