### ISSUE TITLE
deselect when selecting code of another message

### ISSUE THREAD

**Issue by krombel** [quotient-im/Quaternion#300]
As you can see you do not know which piece is currently selected. 
![deselction does not work](https://matrix.org/_matrix/media/v1/download/msgs.tk/UORoTuuWTSynUbaQzkpWpSKS)

When you select another part of the same message deselection works but not for different messages

**Comment by KitsuneRal** [comment]
Selection as well as copy-pasting from the timeline is a complete mess at the moment and it's unlikely to change any time soon :( Basically, there's a choice between enabling that weird selection or disabling selection altogether. I preferred to enable at least this. To fix selection properly one should either change the container used to render the timeline from QML ListView to something more accommodating or do very non-trivial hackarounds, effectively reimplementing selection and copy-pasting. I don't know which is harder, and unlikely to have time even to research it in the nearest couple of months.
