### ISSUE TITLE
read marker is not send when seeing an image which is bigger then the viewable area

### ISSUE THREAD

**Issue by krombel** [quotient-im/Quaternion#305]
When you have an image in your roomview while the readmarker is above that image there is no way to set the read marker to a point below the image when the image is bigger then the viewable area - so the upper border is e.g. not viewable anymore while the lower border is not viewable yet

**Comment by KitsuneRal** [comment]
With #306 fixed this one becomes pretty theoretical. #550 tracks other cases when the message is too high to fit the viewport.
