### ISSUE TITLE
Quaternion crash on start

### ISSUE THREAD

**Issue by progserega** [quotient-im/Quaternion#350]
### Description

Crash at start.
Crash after debug or release build.

### Steps to reproduce

1. Build in qtcreator in release or debug version.
2. Start app
3. Enter login information
4. App connect to matrix and crash

Reproduce - allways.

### Version information
Ubunt 16.04 amd64. 
Build app latest version from git:

 git log|head
commit fff80281413a37c6ce6e3581bf11f695c665fd07
Author: Kitsune Ral <Kitsune-Ral@users.sf.net>
Date:   Tue Apr 17 07:31:31 2018 +0900

    Flatpak: specify KDE runtime version
    
    Closes #348.

Buid by by qtcreator.
QT 5.7.

**Comment by KitsuneRal** [comment]
Just in case, try to rebuild with the latest library (I've just made a commit to Quaternion for your convenience). If it still crashes, can you please switch to the stackframe in `avatar.cpp` and check whether members of `this->d` look sane or the memory is corrupted. Thanks in advance.

**Comment by progserega** [comment]
Thank you! I begin update qt... And check again in debugger.

**Comment by progserega** [comment]
Will check :-)

**Comment by progserega** [comment]
![error2](https://user-images.githubusercontent.com/1297163/39094735-d54d063e-4677-11e8-98ce-9a3114513ca3.png)
I do not found this->d

**Comment by progserega** [comment]
n==null and code call n()...

**Comment by progserega** [comment]
Before rebuild I update qt and git pull to:

commit 35afab10efe2923e6b297e28c0b2a7b9218f4b9d
Author: Kitsune Ral <Kitsune-Ral@users.sf.net>
Date:   Sun Apr 22 18:38:55 2018 +0900

    Update to the latest lib

**Comment by progserega** [comment]
![error3](https://user-images.githubusercontent.com/1297163/39094779-a164c7e8-4678-11e8-8b22-3044e4ad9a6e.png)
may be "d" in _defaultIcon?

**Comment by KitsuneRal** [comment]
Sorry, I messed it - actually I needed `this`. 3 elements in `callbacks` look suspicious but that's all I can see as of yet.

**Comment by KitsuneRal** [comment]
Uhm, hold on, looking at the code in your screenshot - your library is still on the previous commit. Can you please do `git submodule update`?

**Comment by progserega** [comment]
diff --git a/lib/avatar.cpp b/lib/avatar.cpp
index 1ff2aae..1591bfc 100644
--- a/lib/avatar.cpp
+++ b/lib/avatar.cpp
@@ -124,7 +124,10 @@ QImage Avatar::Private::get(Connection* connection, QSize size,
             _originalImage = _thumbnailRequest->scaledThumbnail(_requestedSize);
             _scaledImages.clear();
             for (auto n: callbacks)
-                n();
+            {
+                if(n!=NULL)
+                    n();
+            }
         });
     }

fix this bugs, but this is a hack... :-)

**Comment by KitsuneRal** [comment]
If you go that way, it's better to guard `emplace_back` a few lines before instead :) And indeed I was going to do something like that but still probably crash on assertion for debug mode. That would reveal the abusing caller along the way.

**Comment by progserega** [comment]
After lib update (git pull in lib) and "git submodule update" I rebuild project. Start app and all work good.

Thank you!
