### ISSUE TITLE
scroll slider doesn't continue scrolling when more messages are loaded

### ISSUE THREAD

**Issue by ec1oud** [quotient-im/Quaternion#375]
1. drag the slider all the way upwards
2. hold it there until the scrolling stops: you're now at the oldest message which was already synced
3. keep holding until even older messages get synced from the server
4. it's still stopped, why?

The only way I can tell that the syncing worked is that one more (clipped) message's text gets rendered at the top, but I have to move the slider again to get it scrolling again.

**Comment by KitsuneRal** [comment]
Thanks for the report, will fix it when I get to that code.
