### ISSUE TITLE
Room name: @user:server.org and X others

### ISSUE THREAD

**Issue by aaronraimist** [quotient-im/Quaternion#522]
### Description

Since there is no room name for `#tulirs-watercooler:half-shot.uk` Quaternion calls the room `@Corion:matrix.org, @Mike:matrix.org, @Trinity:matrix.org, and 159 other(s)`. It would be nice if there was a better name for these kinds of rooms

![screen shot 2019-03-03 at 11 33 27 am](https://user-images.githubusercontent.com/5855073/53698955-c75be800-3da8-11e9-9b48-2aa45844e858.png)

There is also no main address/canonical alias so Riot just picks one and uses that as the room name
![screen shot 2019-03-03 at 11 37 12 am](https://user-images.githubusercontent.com/5855073/53698946-b14e2780-3da8-11e9-8980-781971d137d8.png)

### Version information

- **Quaternion version**: 0.0.9.4-beta1
- **Install method**: .dmg
- **Platform**: macOS 10.14.3

**Comment by KitsuneRal** [comment]
Well, what should I say - Riot goes against the spec recommendations:
> Clients SHOULD NOT use m.room.aliases events as a source for room names, as it is difficult for clients to agree on the best alias to use, and aliases can change unexpectedly.
I'm not sure if Quaternion should follow suit and undermine this recommendation further.

**Comment by aaronraimist** [comment]
Ah :(

**Comment by KitsuneRal** [comment]
With that said - I understand that the current representation in Quaternion is suboptimal; let's bring it to spec people and see what they have to say.

**Comment by aaronraimist** [comment]
https://github.com/vector-im/riot-web/issues/7323 Is the Riot issue

**Comment by KitsuneRal** [comment]
After getting rid of `m.room.aliases` event and incorporating [MSC688](https://github.com/matrix-org/matrix-doc/issues/688) the updated spec text [still says](https://matrix.org/docs/spec/client_server/r0.6.1#calculating-the-display-name-for-a-room) that clients should avoid using non-canonical aliases to calculate the display name; and I think that's the best way forward, as we officially wrote non-canonical aliases off as untrusted.
