### ISSUE TITLE
The font in chat time line and some other parts of the UI is too small,  much smaller than i.e. room list or menu bar

### ISSUE THREAD

**Issue by ansorg** [quotient-im/Quaternion#549]
### Description

The font in chat time line and some other parts of the UI is too small,  much smaller than i.e. room list or menu bar. 
![quaternion_font_size](https://user-images.githubusercontent.com/3541784/54663167-9ab20b00-4ae0-11e9-9304-4d37f50959c8.png)

Changing UI/Fonts/render_type to QtRendering changes the appearance slightly but not the font size.

![quaternion_font_size-qtrendering](https://user-images.githubusercontent.com/3541784/54663190-b0273500-4ae0-11e9-8061-344a97c92cb6.png)
### Version information

lib 0.5.0.2, Q 0.0.9.4 beta2
Windows 10 18361.1
Screen resolution 2160 * 1440 
Scaling 100%

**Comment by KitsuneRal** [comment]
Can you please try [the Windows package from CI](https://bintray.com/qmatrixclient/ci/Quaternion/git1324#files) - is it better?

**Comment by ansorg** [comment]
no change.
![image](https://user-images.githubusercontent.com/3541784/54777163-f8924000-4c11-11e9-9bed-27032980d78a.png)
the whole UI is a weird mix of various font sizes on my screen

above with the registry setting and below without

![image](https://user-images.githubusercontent.com/3541784/54777681-2a57d680-4c13-11e9-8849-8d2746318455.png)

**Comment by KitsuneRal** [comment]
I see, thanks. Will investigate further.

**Comment by Xray1870** [comment]
How you have done this to make the font bigger into windows register ?

**Comment by Xray1870** [comment]
> 
> 
> no change.
> ![image](https://user-images.githubusercontent.com/3541784/54777163-f8924000-4c11-11e9-9bed-27032980d78a.png)
> the whole UI is a weird mix of various font sizes on my screen
> 
> above with the registry setting and below without
> 
> ![image](https://user-images.githubusercontent.com/3541784/54777681-2a57d680-4c13-11e9-8849-8d2746318455.png)

How you have done this to make the font bigger into windows register ?

Thanks!

**Comment by KitsuneRal** [comment]
A sort of workaround has just landed in #614. Why such thing is happening in the first place is still a matter of this issue.

**Comment by KitsuneRal** [comment]
With #627 now in the master branch - can you please check if setting the font for the timeline helps?

**Comment by ansorg** [comment]
which build should I try? 
I downloaded quaternion-git1509-win64 but that doesn't work at all, no connection, no error, no log?

**Comment by KitsuneRal** [comment]
I guess this is because we moved over to new OpenSSL in the meantime. Can you please install OpenSSL 1.1.x (you can find links here: https://wiki.openssl.org/index.php/Binaries)?

**Comment by KitsuneRal** [comment]
Also, just for clarity - the font settings should be done directly in the registry at the moment, see https://github.com/quotient-im/Quaternion/#configuration for details.
