### ISSUE TITLE
Can't copy messages

### ISSUE THREAD

**Issue by aaronraimist** [quotient-im/Quaternion#592]
### Steps to reproduce

1. Highlight a message
1. Press your OS's keyboard shortcut to copy or try to right click
1. Nothing happens

Workaround I use is to view source, the keyboard shortcut still doesn't work but at least I get a right click menu with a copy button that does work
 
### Version information

- **Quaternion version**: 0.0.9.4
- **Install method**: .dmg
- **Platform**: macOS 10.14.5

**Comment by KitsuneRal** [comment]
You should be able to do it now, thanks to #606.
