### ISSUE TITLE
windows ssl

### ISSUE THREAD

**Issue by szh7379** [quotient-im/Quaternion#618]
On my win10 x64 device, i need copy libssl32.dll, no only 'ssleay32.dll and libeay32.dll', maybe this can solve the users still get ssl problem. when i just copy the two in readme, i still get ssl context error. if devs can confirm it, maybe you should update the readme.

**Comment by KitsuneRal** [comment]
Thanks. I suppose you use Qt 5.13 and, respectively, OpenSSL 1.1.x?

**Comment by szh7379** [comment]
It is the latest releasle in github, i don't get the Qt version in about menu, OpenSSL is 1.0.2.

**Comment by KitsuneRal** [comment]
Sorry for taking time. There's something wrong here: libssl32.dll and libcrypto32.dll are the new (since OpenSSL 1.1.0) names of ssleay32.dll and libeay32.dll. Are you sure you're using Qt 5.12.2 rather than 5.12.4 or 5.13?

**Comment by KitsuneRal** [comment]
(The difference is that 5.12.4 and 5.13 switched to OpenSSL 1.1 and therefore need libssl32.dll and libcrypto32.dll).

**Comment by szh7379** [comment]
Sorry, i think i made a mistake. with ssleay32.dll and libeay32.dll can't work is the latest release 0.0.9.4c, i did not check the qt version and openssl,  i download nightly build for AppVeyor CI some days later,  replace OpenSSL too, download from https://slproweb.com/products/Win32OpenSSL.html , it contains libssl32.dll in 1.0.2s, i copy it too, i must be confused.
I had tried to remove libssl32, Qt version 5.12.2.0 works.
FYI, i think i used the version <Qt5.12.4 with OpenSSL1.1 in the first time.

**Comment by KitsuneRal** [comment]
Yeah, all that OpenSSL stuff is one huge mess and I'm very sorry that users have to deal with it. Hopefully, we will switch to OpenSSL 1.1 soon enough completely. Anyway, I'll drop a few lines in the documentation to make it very clear which version to use in which case.
