### ISSUE TITLE
Typing notifications with long nicknames force side-panels to shrink

### ISSUE THREAD

**Issue by LEdoian** [quotient-im/Quaternion#632]
### Description

When a user with a long nick starts typing, the typing notification for others does not fit into space designated for it, which in turn enlarges itself horizontally, causing the Rooms and Users panels to shrink.

### Steps to reproduce

- Let User1 and User2 be chatting in some room
- User1: `\roomnick aaaaaaaaaaa....` (four full lines of a's were sufficient for me)
- When User1 starts typing, User2's Quaternion UI shrinks.

### Version information

- **Quaternion version**: 57d3c288fe0ad65022e200d5afd0da1e444de167
- **Qt version**: 5.13.0
- **Install method**: `git pull` (branch `master`), `git submodule update`, `cmake`
- **Platform**: Archlinux with i3-wm

**Comment by KitsuneRal** [comment]
I don't see it reproduced on the current master and Qt 5.14 - can you check please?

**Comment by LEdoian** [comment]
Still happens to me on Quaternion commit 32f697b9b216b25a43da060428fb9e34939ceac4 with Qt 5.15.2-3 from Arch's repositories.

I might be able to test it on some other distro, but can't promise that will happen this week.

**Comment by KitsuneRal** [comment]
Ok, I reproduced it - didn't realise that there should be no whitespaces.
