### ISSUE TITLE
Add formatted mentioning and quotes

### ISSUE THREAD

**Issue by bodqhrohro** [quotient-im/Quaternion#633]
### Description

Riot sends fancy mentions with formatted_body: `<a href=\"https://matrix.to/#/@nickname:server\">nickname</a>:`. Quaternion simply sends `nickname:`, which does not even seem to be recognized as mentions by other clients.

The same applies to quotes. Riot sends `mx-reply` quotes, that include mentioning the quote author. Quaternion is able to display such quotes, but itself it simply prepends `>` when quoting messages.

It would be great to properly mention from Quaternion too.

### Steps to reproduce

Autocompletion:
- type first letters of a nick
- press `Tab`

Clicking:
- click a nickname

Quoting:
- right-click a message
- choose "Quote"

### Version information

- **Quaternion version**: v0.0.9.4+git
- **Qt version**: 5.11.3
- **Install method**: built from source
- **Platform**: Debian 11 GNU/Linux

**Comment by KitsuneRal** [comment]
Thanks for chiming in. Pieces of this are already tracked in various other issues (you're welcome to thumb-up them to raise priority):
- Rich mentions aka "pills": #191 and the pending PR is #580. It's planned to land in 0.0.9.5; there's a good chance you'll see it merged in a week or two when I have another bigger break from my things IRL.
- Rich replies: #447. The full implementation is now somewhere in 0.0.9.6 pipeline and might be postponed even further; instead I might throw in a limited non-spec-compliant implementation. The main problem here is that the spec is unreasonably elaborate in this part and implementing it in full needs tinkering with HTML DOM, and Qt is not very well equipped for that.
