### ISSUE TITLE
Port timeline to Qt Quick Controls 2

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#643]
QQC2 is better at scaling, more lightweight, and QQC1 is deprecated anyway.

**Comment by ognarb** [comment]
I could do it and copy a bit of code from NeoChat, but that would be the required version? Qt 5.9 doesn't have a lot of QQC2 API yet :( Q 5.12 could be a better base to work with.

**Comment by KitsuneRal** [comment]
It is a task for 0.0.9.6 which I intend to build on Qt 5.12 - so yeah, feel free to use 5.12 as the API baseline.

**Comment by KitsuneRal** [comment]
Halfway through, as of 0.0.95 beta 3. The rest is left for 0.0.96.

**Comment by KitsuneRal** [comment]
From #797 (a duplicate of this):
> Qt 6 doesn't have QQC1 and it has more desktop styles for QQC2 - really no excuse to keep any bits around.

**Comment by KitsuneRal** [comment]
Most of the work is done in e721aa41; the timeline is (mostly) workable now, with some QML warnings and dysfunction still around.

**Comment by KitsuneRal** [comment]
As of fa9b95ae and Qt 6.4.3, things look good enough.
