### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by alexbuzzbee** [quotient-im/Quaternion#647]
### Description

According to the hint text in the message send box, Quaternion does not support sending encrypted messages. This makes it unusable for me, as all of my personal conversations are encrypted.

I cannot use Quaternion until it supports encrypted messages. This is a shame, since it otherwise seems like an excellent client.

When I looked for an existing issue, I couldn't find one. If one does exist, go ahead and close this as a duplicate and I'll comment on the existing issue.

### Steps to reproduce

- Install Quaternion via Flatpak without changing any configuration.
- Launch the Flatpak Quaternion.
- Open an encrypted chat created with a different client.
- Note that the "send message" box is disabled and states that "Sending encrypted messages is not supported yet.

I expected that Quaternion would support encrypted messages; they are a rather basic and very commonly-used feature of Matrix.

### Version information

- **Quaternion version**:

```
$ flatpak info com.github.quaternion

Quaternion - Qt5-based client for Matrix networks

          ID: com.github.quaternion
         Ref: app/com.github.quaternion/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.9.4
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.4 MB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 1295ec3fabfbd9a456be618bd44c010640b9e29c2785708178a47bbf4db822b3
      Parent: e1595f717fc6e90bf4895729459e49d22bc6fe2c182911ae51277dcd5f3bded6
     Subject: 0.0.9.4c (6bd365b0)
        Date: 2019-05-23 11:50:30 +0000
```

- **Qt version**: Probably the version included in the Flatpak. Flatpak did not install a separate copy of Qt. The system Qt is 5.13.2.

- **Install method**: Installed using the Flatpak instructions in the README.

- **Platform**: I am using an up-to-date version of Void Linux, a rolling-release distribution with atypical software selections.

**Comment by aaronraimist** [comment]
Thanks for filing. #75 is the existing issue so you can add a thumbs up and comment there.
