### ISSUE TITLE
repository version for ubuntu 18.04 doesn't seem to install qml properly

### ISSUE THREAD

**Issue by pretentious7** [quotient-im/Quaternion#668]
### Description

so I have the issue in which messages are invisible even though sending works.

this is is quaternion logs.

qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
qrc:///qml/chat.qml:1:1: module "QtQuick" is not installed
qrc:///qml/chat.qml:4:1: module "QtQuick.Layouts" is not installed
qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
qrc:///qml/chat.qml:1:1: module "QtQuick" is not installed
qrc:///qml/chat.qml:4:1: module "QtQuick.Layouts" is not installed
qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
qrc:///qml/chat.qml:1:1: module "QtQuick" is not installed
qrc:///qml/chat.qml:4:1: module "QtQuick.Layouts" is not installed
qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
qrc:///qml/chat.qml:1:1: module "QtQuick" is not installed
qrc:///qml/chat.qml:4:1: module "QtQuick.Layouts" is not installed

### Steps to reproduce
-sudo apt install quaternion
-quaternion

### Version information

- **Quaternion version**:
- **Qt version**: 
- **Install method**: apt
- **Platform**: Ubuntu 18.04

**Comment by KitsuneRal** [comment]
I'm afraid bionic has an extremely old version of Quaternion (0.0.5), and usually Quaternion packages are taken from Debian... @uhoreg, do you have an idea how this can be reasonably helped? I don't know how the process between Debian and Ubuntu works, honestly.

**Comment by uhoreg** [comment]
I don't know much about how Ubuntu works, but I believe that once a release is cut, packages aren't updated for that release any more, other than security updates.  It looks like later ubuntu releases have picked up more recent versions of quaternion.

**Comment by uhoreg** [comment]
It looks like the package in bionic is missing a dependency on `qml-module-qtquick-controls`.  Try doing `sudo apt install qml-module-qtquick-controls`

**Comment by pretentious7** [comment]
> I don't know much about how Ubuntu works, but I believe that once a release is cut, packages aren't updated for that release any more, other than security updates. It looks like later ubuntu releases have picked up more recent versions of quaternion.

ah I see, I had to downgrade because 19.10 just decided to randomly break logins and such on my computer. Would you recommend just installing from source or flatpak?

**Comment by pretentious7** [comment]
I figured it should just work cause it is in the repo, can this be added as a dependency? I'm not quite sure how repositories are maintained.

**Comment by KitsuneRal** [comment]
I guess you have to try to chase whomever takes care of it in Ubuntu. Judging by [the package page](https://packages.ubuntu.com/bionic/quaternion), the proper way is to [file a bug](https://bugs.launchpad.net/ubuntu/+source/quaternion/+filebug) on the package. You can refer them to the same package in disco (19.04) that has this dependency included.
