### ISSUE TITLE
[Feature Request] Add search in main window 

### ISSUE THREAD

**Issue by pretentious7** [quotient-im/Quaternion#669]
### Description

I'd like to see a search feature for the chat, as this doesn't seem to exist right now and would be useful. 

### Version information

- **Quaternion version**: 0.0.9.4
- **Qt version**: 
- **Install method**: Flatpak
- **Platform**: Ubuntu 18.04

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/quotient-im/Quaternion/issues/258, please thumbs up that issue
