### ISSUE TITLE
Crash after changing message display in timeline

### ISSUE THREAD

**Issue by krkk** [quotient-im/Quaternion#671]
### Steps to reproduce

- open a room
- change any option in View->Display in Timeline

It looks like removing `Q_ASSERT(contextKey);` in `KChatEditPrivate::makeDocument()` fixes this, but I'm not sure if this is the right way to do it.
https://github.com/quotient-im/Quaternion/blob/b98fbfd0c98cbdc691665d31ad34018b047d83b8/client/kchatedit.cpp#L31-L35

**Comment by KitsuneRal** [comment]
An assertion is there for a reason. Reproducing.

**Comment by KitsuneRal** [comment]
Thanks for reporting, bug found and extinguished.
