### ISSUE TITLE
Flathub package is eight months out of date

### ISSUE THREAD

**Issue by tidux** [quotient-im/Quaternion#683]
Please start pushing Flatpaks again.

**Comment by KitsuneRal** [comment]
For that to happen I have to get to building a fresh build of Quaternion that wouldn't be on a master branch. I'm closing in to that but you'll probably have to wait another month.

**Comment by KitsuneRal** [comment]
Hm, now that I take a closer look at it... I actually released a stable branch update on the 1st of April, perhaps I should've at least pushed that to Flathub.

**Comment by KitsuneRal** [comment]
Hm, wait, I [did push it](https://github.com/flathub/com.github.quaternion/commit/73f82cba299dfed9c9d557823e2fcdd1cd96e00d), actually.

**Comment by tidux** [comment]
Weird, it didn't show up.  Maybe you have to increment the version for Flathub to repackage it?

**Comment by ptman** [comment]
IIRC you had to remove and reinstall it.

**Comment by KitsuneRal** [comment]
Well I did change the version, from 0.0.9.4 to 0.0.9.4e... Can it be something around the version number?

**Comment by KitsuneRal** [comment]
The Flathub website actually says it's been updated more than a year ago, back when the original 0.0.9.4 was released...

**Comment by KitsuneRal** [comment]
Just tried to install it myself, and 0.0.9.4e gets installed. You should probably work with Flathub on figuring out what's wrong with non-numeric version postfixes.
