### ISSUE TITLE
Allow user to select 12 hour or 24 hour timestamp format

### ISSUE THREAD

**Issue by jg110** [quotient-im/Quaternion#696]
### Description

This is a feature request for displaying timestamps in 12 hour format.

### Version information

- **Quaternion version**: 0.0.9.4e
- **Qt version**: 5.14.2 
- **Install method**: Package manager
- **Platform**: Fedora 32, Linux 5.7.16

**Comment by KitsuneRal** [comment]
Hm, it seems that Quaternion doesn't quite respect the locale in this part.

**Comment by jg110** [comment]
Looks good, I just built the most recent commit and timestamps are now in 12 hour format. Thanks.
