### ISSUE TITLE
Crash with the latest git version of Quaternion

### ISSUE THREAD

**Issue by as400l** [quotient-im/Quaternion#700]
I have compiled Quaternion from source and when I try to run it I get:

```
Must construct a QGuiApplication before accessing a platform theme hint.
Must construct a QGuiApplication before accessing a platform theme hint.
“quaternion &” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by KitsuneRal** [comment]
I see - thanks for reporting. Qt documentation seems to be a bit confusing in this regard, and I apparently refactored the code the wrong way.

**Comment by KitsuneRal** [comment]
For the record, what's your environment (OS, window system...)

**Comment by as400l** [comment]
I'm on Manjaro Plasma (KDE).

**Comment by KitsuneRal** [comment]
And do you run Quaternion from a Flatpak or directly on the system?

**Comment by as400l** [comment]
Directly on the system. I compiled native arch package from your git repo.

**Comment by KitsuneRal** [comment]
Thanks, I'll look into this. Direct builds should not have been affected in the first place.
