### ISSUE TITLE
Quaternion hangs when trying to login, related to missing OpenSSL DLL

### ISSUE THREAD

**Issue by nyanpasu64** [quotient-im/Quaternion#703]
### Description

When I type my Matrix ID into the login dialog and click Login, it never finishes.

### Steps to reproduce

- Open Quaternion without an account configured. The Login dialog will popup.
- Type matrix ID, password, random device name, and press Login.

The login dialog changes to "Connecting and logging in, please wait" and the widgets are disabled, but the dialog can still be closed. Around 90 seconds later, it changes to "Error creating SSL context ()" and the widgets are enabled again.

I built git master. When entering `@username:matrix.org`, it tries to send a TLS request to https://matrix.org/.well-known/matrix/client. However it prints a "tls initialization failed" error to stdout, since I don't have an OpenSSL DLL in PATH.

I installed `libcrypto-1_1[-x64].dll` to PATH, which fixed git master (I can login now). However, release 0.0.9.4e (which does not ship with libcrypto) still hangs on login, even with libcrypto in PATH.

### Version information

- **Quaternion version**: Latest 0.0.9.4e, master 62a073367c528c9ae9d9156977f909e91b909ccd
- **Qt version**: Qt 5.15.1 x64
- **Install method**: GitHub Releases, build from source (MSVC)
- **Platform**: Windows 10 x64 1909

**Comment by KitsuneRal** [comment]
If it's about 0.0.9.4e binaries taken from GitHub then I _think_ (can't check as I'm not on Windows anymore) it still used OpenSSL 1.0, not 1.1 - and you should add libeay/ssleay libraries instead. The way you can check it is to run Quaternion from under `depends.exe` tool and see what kind of libraries show up when you try to login.

**Comment by KitsuneRal** [comment]
Actually, I found the logs from building 0.0.9.4e - and yes, that build is done with Qt 5.11 that, I think, only works with OpenSSL 1.0 (meaning that heh, I must release 0.0.9.4f ASAP to jump off the unsupported OpenSSL version). But if you build 0.0.9.4e yourself - I have no idea what could be an issue.

**Comment by KitsuneRal** [comment]
Also, since finding the right OpenSSL version on Windows seems to be [even more a hit-and-miss](https://stackoverflow.com/questions/58625924/qt-error-message-qt-network-ssl-qsslsocketconnecttohostencrypted-tls-initia) than I previously thought I'm going to take notice and add the debug logging mentioned in the linked StackOverflow answer. I doubt it's that wrong when you build with Qt 5.12 or newer but dumping a version string to logs is never a bad idea.

**Comment by KitsuneRal** [comment]
Should be fixed by [0.0.9.4f](https://github.com/quotient-im/Quaternion/releases/tag/0.0.9.4f).
