### ISSUE TITLE
Sluggish chat window scrolling

### ISSUE THREAD

**Issue by kcat** [quotient-im/Quaternion#711]
### Description

Compared to other apps, scrolling the chat window with my mouse's scroll wheel is significantly slower. My web browser (Pale Moon), IM client (Pidgin), IRC client (Konversation), and text editor/IDE (Qt Creator) are all pretty nappy and responsive when using the scroll wheel, but Quaternion is rather sluggish in comparison, with each "tick" of the wheel moving a much smaller amount than other apps.

### Version information

- **Quaternion version**: 0.0.9.4e
- **Qt version**: 5.14.2
- **Install method**: Debian repository
- **Platform**: Debian Linux w/ KDE5

**Comment by KitsuneRal** [comment]
Somewhat related: #313 (though ideally the scrolling speed should not need adjustments but just be aligned with the rest of the system).

**Comment by bearbin** [comment]
This is still an issue. All that's needed is for the scroll speed to be the OS's normal speed, I think the DE allows enough configurability that app-specific scroll speed needn't be a priority.

**Comment by KitsuneRal** [comment]
Ideas how to apply "OS default scroll speed" to QML ListView are very welcome. Unfortunately, that's one of cases where an otherwise awesome piece of technology doesn't work as it's supposed to and needs workarounds; and the current one is not working well across platforms/input devices either.

**Comment by RoboMWM** [comment]
Update: I'm also noticing this exact same scrolling behavior in Nheko, so I assume this is some Qt thing instead.

---

Not sure if this has been fixed, but I'm observing this issue. I can also repost in #313 (or perhaps there's another issue on this that search didn't catch?), but I'm curious if https://github.com/quotient-im/Quaternion/commit/441d27552dcaabbeced91f724f3cb6f7c18d4443 actually did anything (or if I'm just not understanding it properly) as I observe it scrolling "slower" the faster I attempt to scroll.

v0.0.97.1
Built from Git, commit SHA:
`53be5b207c899e3393e5e3702d66fe315eb73a07`

Library commit SHA:
`c02f719716b8cff20e17e49a26fb9e34f0719692`

Qt version 6.6.3

<img width="302" height="360" alt="Image" src="https://github.com/user-attachments/assets/8423b133-ba38-423c-88b0-88ec4055c2ec" />

Videos: first is fast mousewheel scroll, second is slow mousewheel scroll.

Quaternion: https://github.com/user-attachments/assets/cb1a1ee4-a2af-4a6c-a0ee-d1fcaf2c6cab
Discord for reference: https://github.com/user-attachments/assets/d68f3b8e-321c-432b-9207-99a58416a55f

(Hmm, doesn't show up as well with the 30fps recording, but comparison should be noticeable.)
