### ISSUE TITLE
Disappearing scrollbar

### ISSUE THREAD

**Issue by kcat** [quotient-im/Quaternion#712]
One thing I'm really liking about Quaternion is it actually looks and behaves more like a proper desktop app compared to other Matrix clients. To that end, I've disabled the "shuttle scrollbar" (and restarted), to have a more traditional style scrolling chat window. While this did get rid of the shuttle scrollbar and give a more regular style one, the scrollbar only appears when scrolling, then fades away after a moment. Once it fades away, it doesn't come back until you scroll again, making it impossible to click and drag it without first scrolling with the scroll wheel to make it appear.

Additionally, the scrollbar overlays UI elements on the right side of the window, making it difficult to know what you're clicking when you try to grab the scrollbar. The scrollbar also looks different to and is much wider than the scrollbar that's been set by the KDE/Qt desktop UI theme.

### Version information

- **Quaternion version**: 0.0.9.4e
- **Qt version**: 5.14.2
- **Install method**: Debian repository
- **Platform**: Debian Linux w/ KDE5

**Comment by grahamperrin** [comment]
I have no scroll wheel so this is close to a show-stopper: 

![image](https://user-images.githubusercontent.com/192271/103240169-75a22b80-4947-11eb-8a68-f016196b4df6.png)

```text
mowa219-gjp4-8570p% date ; uname -v                     
Mon 28 Dec 2020 19:59:56 GMT
FreeBSD 13.0-CURRENT #74 r368589: Sun Dec 13 07:55:46 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
mowa219-gjp4-8570p% pkg query '%o %v %R' quaternion
net-im/quaternion 0.0.9.5.b1 FreeBSD
mowa219-gjp4-8570p% 
```

**Comment by KitsuneRal** [comment]
The intention was that the "classic" scroll bar still appears if you hover on the area where it should show up. Perhaps I really should keep it on the screen instead. As for its visuals - not sure if I can do much about them, this is what Qt's QML engine gives me. Unfortunately, there's literally no way to make the scroll bar look exactly as the one for rooms on the left since different engines are used to render those (whatever eyebrows that would raise).

**Comment by grahamperrin** [comment]
Thanks, 

> … hover …

I imagined it appearing when pointing but (above) it doesn't. I see the bar for maybe a split-second after selecting a room, then it might reappear when I begin moving the pointer (away from the sidebar list of rooms) towards the right of the window, but it never appears when pointing at where it should appear. 

> … what Qt's QML engine gives me …

I didn't intend to raise a separate issue, but I do find the shuttle scrollbar uncomfortably narrow, which increases the desire for an always-on traditional scrollbar.

**Comment by grahamperrin** [comment]
> … might reappear when I begin moving the pointer (away from the sidebar list of rooms) towards the right of the window, … 

Ignore that. The reappearance coincided with receipt of a message, which triggers appearance of the bar. 

The bar also appears when resizing the window, but this is a clumsy workaround.
