### ISSUE TITLE
Link URL detection does not work always

### ISSUE THREAD

**Issue by vranki** [quotient-im/Quaternion#726]
Some links pasted by IRC users are not interpreted as links and need to be manually copy-pasted to a browser to open them. That is quite annoying.

Here are 2 examples of links pasted by IRC users, as seen by Matrix client (raw body):
```
https://scontent-arn2-2.xx.fbcdn.net/v/t1.0-9/56894369_10156484881641387_7100980223453167616_n.jpg?_nc_cat=102&amp;_nc_ht=scontent-arn2-2.xx&amp;oh=9ccb15390232a379df203c9ede3fffb4&amp;oe=5D458A3F

<span style='white-space:pre-wrap'><a href="https://www.iltalehti.fi/kotimaa/a/c1c90665-2486-4537-b659-1a5ad58fe549">https://www.iltalehti.fi/kotimaa/a/c1c90665-2486-4537-b659-1a5ad58fe549</a></span>
```
Notice that the first one does not have any HTML tags including to make it a link. Second one has. If I understand correctly, the library's URL detection code does not detect these links for some reason.

Some other URLs not detected:

https://www.aamulehti.fi/a/cf208478-5638-416b-823e-3e2cf3762a0c

https://www.tori.fi/pirkanmaa/Ylakaappi__lev_100cm__syv_60cm_ovet_55727586.htm?ca=18&w=111

https://www.youtube.com/watch?reload=9&v=Dr20f19czeE

The issue is probably caused by util.cpp's linkifyUrls() function. We tested that from Matrix users the links seem to work, for example https://www.aamulehti.fi/a/cf208478-5638-416b-823e-3e2cf3762a0c pasted by Matrix user becomes:

```
<span style='white-space:pre-wrap'><a href="https://www.aamulehti.fi/a/cf208478-5638-416b-823e-3e2cf3762a0c">https://www.aamulehti.fi/a/cf208478-5638-416b-823e-3e2cf3762a0c</a></span>
```
Probably the incoming htmlEscapedText is different for IRC & Matrix users somehow.

**Comment by KitsuneRal** [comment]
As for Quaternion, URLs in formatted messages were not detected before, and that was a deliberate decision (I didn't want to parse HTML). Recently, though, Quaternion gained HTML parsing capabilities, so things are linkified as expected in _almost_ every case except when the entry is parsed as Markdown. It's not entirely clear whether Qt is at fault here or the preprocessing performed in Quaternion throws a wrench with unnecessary (or insufficient) escaping.

**Comment by KitsuneRal** [comment]
This seems to be fixed after all the work for beta4.
