### ISSUE TITLE
Parse markup on input

### ISSUE THREAD

**Issue by maralorn** [quotient-im/Quaternion#73]

**Comment by KitsuneRal** [comment]
I wonder which markup you implied but recent 0.0.95 betas can actually parse both HTML and (if compiled with Qt 5.14 or newer) Markdown. Perhaps this can be closed?

**Comment by KitsuneRal** [comment]
Related: #421, #730.

**Comment by maralorn** [comment]
Oh, wow. I have no idea what four-years-ago-maralorn thought by that. That issue is offensively inverbose. But I am pretty sure I thought of markdown back then.

Please don‘t mind me either way, close this issue ad libidum.
