### ISSUE TITLE
sanitize "Join Room" input (e.g. whitespace removal)

### ISSUE THREAD

**Issue by tverrbjelke** [quotient-im/Quaternion#743]
### Description

joining " #nheko:matrix.org" results to error instead joining #nheko:matrix.org
(^--- leading space from clipboard in channel name should definitely be sanitized)

### Version information

- **Quaternion version**: v0.0.9.4e
Built from Git, commit SHA:
e5f856cb17bcae401530cd773e855fb596a5b3c9
(Oh lord, please also change so to MAKE THIS VERSION INFO-TEXT "v0.0.9.4e "in About menu  _text-selectable_ !!!)

- **Qt version**: 
If you need this Version info, please provide with the Help->About menu, maybe where the link to QT website is) No precious issue providing user should not be bothered with such system-gritty info - when you simply can provide the info by yourself in the Program!
For me as "dumb user" it is somewhat complicated, since using debian stretch and installed the program via flatpack, how am I expected to provide such highly dynamic information without further assistance?
(Sorry for being picky, I _am_ trying to help... but ... )

- **Install method**: 
flatpack
- **Platform**: 
Linux debian

**Comment by KitsuneRal** [comment]
Thanks for reporting. The version currently in the works validates input so it just won't let you do anything before you remove that whitespace. That said, it would be even more usable if leading and trailing whitespaces were simply ignored.

On selectability in the About dialog - good catch, will also do that.

To get the Qt version, the current beta provides a separate "Help -> About Qt" box that shows all the necessary information.
