### ISSUE TITLE
Release 0.0.95 beta 5

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#766]
Pre-check:
- [x] There are no pending issues for this beta (if there are, move them away)
- [x] Check the latest branch/commit:
  - [x] in the Quaternion repo
  - [x] in the Quotient repo (mind `super-project-pointer`)
  - [x] ![GitHub Actions](https://github.com/quotient-im/Quaternion/workflows/CI/badge.svg)
- [x] Make sure dependent versions in `CMakeLists.txt` are up-to-date (Quotient, Qt Keychain)
- [x] [Pull translations](https://lokalise.co/download/730769035bbc328c31e863.62506391/)
- [x] Check that contents of README.md, SECURITY.md, and BUILDING.md are up-to-date
- [x] Rebuild and smoke-test the application
- [x] Push changes in the translation base, if any

Actions:
- [x] Update the version number in `main.cpp` and `CMakeLists.txt`
- [x] Go to the [Releases page](https://github.com/quotient-im/Quaternion/releases) and make a draft for release notes:
  - [x] Thank all contributors whose commits landed in this release
  - [x] Describe notable fixes/enhancements
  - [x] Make sure to check pre-release checkbox if it's beta/RC
- [x] `git commit && git push`
- [x] Finalise the release at GitHub:
  - [x] Fill in the tag (plain version, no more leading `v`/`rc`)
  - [x] Publish release notes
- [x] Update [Flathub repo](https://github.com/flathub/com.github.quaternion), beta branch
- [x] Update the topic in #quaternion
- [x] Post a TWIM update

Post-release:
- [x] Open the release page in Incognito/Privacy mode; check:
  - [x] the version (should be "Version ###")
  - [x] the Git tag
  - [x] download AppImages and smoke-test
- [x] Add '+git' to the version number in 'main.cpp'
- [x] `git commit && git push`
- [x] Enable GitHub bot in `#quotient`

- [x] Congratulate everyone and have a drink :)

**Comment by aaronraimist** [comment]
Might want to add a step: if a beta/rc, check the pre-release checkbox on the GitHub release.

Some people have automated bots that will submit PRs to update things in Homebrew. so  if it is not marked as a pre-release then Homebrew gets updated to use the beta instead of the latest stable version.

**Comment by KitsuneRal** [comment]
Makes sense, thanks. You're also welcome to contribute this to the [release checklist template](https://github.com/quotient-im/Quaternion/wiki/Release-checklist).

**Comment by KitsuneRal** [comment]
Turns out that CI unsets that flag, which explains why I constantly found myself wondering how I could be so careless. Worth making it more intelligent.
