### ISSUE TITLE
Login - TLS initialization failed

### ISSUE THREAD

**Issue by smaragdus** [quotient-im/Quaternion#794]
I tried to update [Quaternion](https://github.com/quotient-im/Quaternion) from version [0.0.9.4e](https://github.com/quotient-im/Quaternion/releases/tag/0.0.9.4e) to version [0.0.9.4f](https://github.com/quotient-im/Quaternion/releases/tag/0.0.9.4f) but I could not log in, because there was an error:

- `TLS initialization failed`

**screen:**

![Quaternion 0 0 9 4f - 2021-09 - error - 002](https://user-images.githubusercontent.com/9025757/133865735-bd4736be-e2f3-4c4d-95e7-e216b719a6ef.png)

The same error happened with version [0.0.95 RC4](https://github.com/quotient-im/Quaternion/releases/tag/0.0.95-rc4).

I also noticed that **About** window for version **0.0.9.4f** shows wrong version - **0.0.9.4e**.

I have no problem logging in using version **0.0.9.4e**:

 **screen:**

![Quaternion 0 0 9 4e - 2021-09 - 002](https://user-images.githubusercontent.com/9025757/133866012-1f8352f2-973d-481d-95f8-e16fc83d953b.png)

However another error appears:

- `Quaternion couldn't restrict permissions on the access token file. Do you still want to save the access token to it?`

**screen:**

![Quaternion 0 0 9 4e - 2021-09 - error - 001](https://user-images.githubusercontent.com/9025757/133866608-2cf27967-91d7-4733-8ae4-342047a23b2f.png)

Testing different versions of **Quaternion** is not easy because it saves its settings in Windows registry, and in different in keys:

- **Quaternion** version **0.0.9.4e** - `HKEY_CURRENT_USER\Software\Quaternion\quaternion`
- **Quaternion** version **0.0.9.4f** - `HKEY_CURRENT_USER\Software\QMatrixClient\quaternion`

Deleting the keys and starting anew did not help, log in problem persisted.

These problems happen on **Windows 8 x64**.

So for the time being I can only use **Quaternion** version **0.0.9.4e** since **Quaternion** version **0.0.9.4f** fails to log in.

**Comment by KitsuneRal** [comment]
The TLS error is due to an unfortunate but required switch to the new OpenSSL version.  Please take a look at Quaternion README file (you can find him in the GitHub repo) regarding the particular version required. I also strongly recommend to use 0.0.95 RC4: despite being a pre-release, it is much better and more stable in many respects than 0.0.9.4.

**Comment by smaragdus** [comment]
@KitsuneRal 

Thanks for the tip. I used the binaries provided on [this site](https://slproweb.com/products/Win32OpenSSL.html) and I was able to log in.

Regards
