### ISSUE TITLE
cmake build --target clean deletes quaternion_en.ts

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#795]
Seems to be a side-effect of `quaternion_en.ts` being passed to `qt5_create_translation()` - that macro comes useful to update the file but as a result CMake marks it as `GENERATED`(?), and generated files are supposed to be deleted on cleaning.

**Comment by queria** [comment]
I'm not sure, new to these things, but seems this file does get regenerated every time - with line positions changing inside whenever code change/patch is applied ... so maybe this file should be excluded from the repository and always generated at compile time?

**Comment by KitsuneRal** [comment]
Looks like this was a bug in Qt(?) and it was fixed - doesn't reproduce any more.
