### ISSUE TITLE
Quaternion white chat widget

### ISSUE THREAD

**Issue by arichiardi** [quotient-im/Quaternion#811]
### Description

When you open Quaternion, you see white chat rooms.

I know this one was reported already but this seems different and wanted to log it for others to benefit from the solution.

### Steps to reproduce

Open Quaternion and select a chat room. You won't see messages (and in my case I would see white background).

The logs show:

```
Rendering QML with QQuickWidget
qrc:/qml/Timeline.qml:4:1: module "QtGraphicalEffects" is not installed 
     import QtGraphicalEffects 1.0 // For fancy highlighting 
     ^
--- Show time!
```

### Version information

- **Quaternion version**: 0.0.95.1
- **Qt version**:  5.15.2 
- **Install method**: archive downloaded 
- **Platform**: Linux/Manjaro

**Comment by arichiardi** [comment]
Answering to my own issue :smile: 

I just had to install the library called `qt5-graphicaleffects` on Arch.

That solved! Closing :smile_cat:

**Comment by KitsuneRal** [comment]
Is that documented in Quaternion repo though?.. It doesn't seem to be Arch-specific, RHEL has `qt5-qtgraphicaleffects` too, e.g.
