### ISSUE TITLE
White chat widget on windows release

### ISSUE THREAD

**Issue by iglosiggio** [quotient-im/Quaternion#813]
### Description

The chat window is completely empty. The debug log says that both QtQuick.Layouts and QtQuick.Controls are missing (this is using the windows release).

### Steps to reproduce

- Uncompress the zipfile and add the openssl dlls
- Launch the program and login to your account

### Version information

- **Quaternion version**: 0.0.95.1
- **Qt version**: 5.15.2
- **Install method**: Zip download from the github releases tab
- **Platform**: Windows (x64)

**Comment by iglosiggio** [comment]
I ended up downloading some prebuilt dlls from https://github.com/martinrotter/qt-minimalistic-builds and the client seems to work w/that :(

**Comment by KitsuneRal** [comment]
Thanks for reporting; I'll check these out. Surprising that it's only been reported now.

**Comment by iglosiggio** [comment]
The artifact for https://github.com/quotient-im/Quaternion/commit/270ea22e4fdb761901bab6247a5ead2813130664 worked on my machine 😄

**Comment by KitsuneRal** [comment]
That's... weird. The two archives (0.0.95.1 and this one) are identical, except the top-level directory name.

**Comment by iglosiggio** [comment]
🤷

**Comment by iglosiggio** [comment]
@KitsuneRal now i can't reproduce the issue.
It might be some issue during initialization? (like... on the first startup of the program)

That would explain why this wasn't reported earlier.

**Comment by KitsuneRal** [comment]
I don't think so. QML imports are quite static, so every time the same set of libraries is needed. Did you unpack the whole set from qt-minimalistic-builds or just some files?

**Comment by iglosiggio** [comment]
Just the folders for QtQuick and QtQuick2.
