### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by mad-max-traveller** [quotient-im/Quaternion#819]
### Description

Hi. Help me find the application configuration file. It is not in the home directory: user-specific: $HOME/.config/Quotient/quaternion.conf

### Version information

- **Quaternion version**: 0.0.95.1
- **Qt version**: 5.15
- **Install method**: Flatpak
- **Platform**: Linux

$ flatpak info com.github.quaternion

Quaternion - Qt5-based client for Matrix networks
              ID: com.github.quaternion
          Ссылка: app/com.github.quaternion/x86_64/stable
     Архитектура: x86_64
           Ветка: stable
          Версия: 0.0.95.1
        Лицензия: GPL-3.0+
        Источник: flathub
       Коллекция: org.flathub.Stable
       Установка: system
     Установлено: 10,7 MB
Среда исполнения: org.kde.Platform/x86_64/5.15
             Sdk: org.kde.Sdk/x86_64/5.15
          Коммит: 89da88d02d427f6ba2e012677a98110d604f1e62302c29f25cbe12e300ea1d0b
        Родитель: 04e16089a4d1bc8e4dee441eb5794c3149686adb6a5a226deedcf9a0b83e390c
       Заголовок: Rebuild of 0.0.95.1 with the compliant screenshot (4daed992)
            Дата: 2021-10-08 14:17:00 +0000

$ flatpak info org.kde.Platform

KDE Application Platform - Shared libraries used by KDE applications
         ID: org.kde.Platform
     Ссылка: runtime/org.kde.Platform/x86_64/5.15
Архитектура: x86_64
      Ветка: 5.15
   Лицензия: GPL-2.0+
   Источник: flathub
  Коллекция: org.flathub.Stable
  Установка: system
Установлено: 1,0 GB
     Коммит: dc1c3d01cc95b500c9c334e7e54cf80e2179ac5ab53f2e3fbc63cc7e34ecd448
   Родитель: 1cb4374f4cc2438ca9674ae683b38fb1dbe74704d28cd8508349c81f6228b3d3
  Заголовок: build of org.kde.Sdk, Fri 11 Feb 2022 03:00:53 PM UTC (a635bbeddbec37fcc3e35484636f0f549798d2bb)
       Дата: 2022-02-11 23:20:19 +0000

**Comment by opk12** [comment]
Check `$HOME/.var` (for more info see [here](https://github.com/flatpak/flatpak.github.io/issues/191) and [here](https://unix.stackexchange.com/q/460187)), otherwise `strace -f quaternion 2>&1 | grep access | grep quaternion.conf | grep -v -- -1`

**Comment by mad-max-traveller** [comment]
Thank you for your help.
