### ISSUE TITLE
Quaternion crashes shortly after attempting to load room logos (Haiku)

### ISSUE THREAD

**Issue by win8linux** [quotient-im/Quaternion#829]
### Description

Quaternion crashes shortly after launching it on Haiku

### Steps to reproduce

- Install Quaternion package from HaikuDepot
- Launch Quaternion

Expected:
Quaternion loads the room logos and finishes starting up successfully.

Quaternion dumps logs to the standard output. If you can find the logs and
identify any log snippets relevant to your issue, please include
those here (please be careful to remove any personal or private data):

These are the last lines before Quaternion crashes, which happen after its gets the list of rooms:
```
quotient.jobs.sync: Sent GET https://kde.modular.im/_matrix/client/r0/sync
quotient.jobs: Sent GET https://kde.modular.im/_matrix/client/r0/capabilities
quotient.jobs: Sent GET https://kde.modular.im/_matrix/media/r0/thumbnail/matrix.org/KZPqBntPhSHznmEefXrIdadx
quotient.jobs: 200 <- GET https://kde.modular.im/_matrix/client/r0/capabilities
quotient.jobs.sync: 200 <- GET https://kde.modular.im/_matrix/client/r0/sync
Kill Thread
```

There is also the crash report generated by Haiku:
https://gist.github.com/win8linux/df34f621e5b3f87ebd3203dcca14839d

### Version information

- **Quaternion version**: 0.0.95
- **Install method**: Package Manager (HaikuDepot from official HaikuPorts repo)
- **Platform**: Haiku `x86_64`

**Comment by KitsuneRal** [comment]
The related piece of the stacktrace (`RoomEvent::senderId()` and below) is very well-trodden so I venture guessing there's an issue in the Haiku port of Qt.
