### ISSUE TITLE
Login duplicates

### ISSUE THREAD

**Issue by artenax** [quotient-im/Quaternion#830]
### Description

After each new launch of Quaternion there is a line about the new login in the list of recent logins (which I look in app.element.io). There are 85 of them now.
The password is saved in Quaternion. Quaternion is used by my brother (on Windows). There is no such thing in my Linux build.

### Steps to reproduce

- Launch Quatrenion on Windows
- Chatted
- Closed Quatrenion
- Repeated this several times, every day

- Opened the browser
- Logged in to app.element.io
- Opened Security section
- There are many duplicates of Quatrenion in the list of recent (active) logins
- I delete the old ones, but it repeats

I expect there should be one login. Like in the Linux version.

### Version information

- **Quaternion version**: 0.0.95.1
- **Install method**: archive downloaded from this site https://github.com/quotient-im/Quaternion/releases + OpenSSL from here https://slproweb.com/products/Win32OpenSSL.html Win64 Installer Light. I don't remember the version, I think it's 1.1.1
- **Platform**: Windows 7 SP1 x64 with all updates.
- Private chat (room for two of us) without E2E encryption, matrix.org server.

**Comment by artenax** [comment]
I don't think my brother enters/copies the password every time. But I will ask him, even though it won't be easy. Maybe there is a login window on Windows, but the login/password form is already filled out?
UPD: He said he copies the password manually every time o_O

**Comment by KitsuneRal** [comment]
Well, then he legitimately creates a completely new login session every time :-D
Suggest to him to tick the box "Stay logged in" - the password won't be sent or stored, only the access token will, and even that one in the Windows secure storage.
It may make sense for Quaternion to log out if a given account is not marked for staying logged in though.

**Comment by artenax** [comment]
Yes, it seems to be about security. Before that, we were using messengers that had an autologin.

By the way, I compiled Spectral for Linux (there is no build for Windows). And I think it connects to the server (displays chat) faster than Quaternion. Although, they both use libQuotient. But Spectral's libQuotient is older, as the program is abandoned. Maybe you could work in that direction, if it's about the GUI? Or maybe it's a caching.
Strange thing: If I often run Spectral, the server logs me out. Probably because of an invalid command. So, I have two messengers.

**Comment by KitsuneRal** [comment]
The sessions not marked for staying logged in are logged out, as of 0.0.96 beta (namely, b07fd1ad).
