### ISSUE TITLE
Files pasted from the clipboard don't have an extension

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#835]
### Description

Quaternion uses a temporary file name that has no extension to keep the file inserted from the clipboard. It would be better to also take the MIME type from the clipboard and derive an extension from that.

### Version information

- **Quaternion version**: 0.0.95.1

**Comment by ghost** [comment]
What do you want to use the extension for? Can't the mime type be stored?

**Comment by KitsuneRal** [comment]
This file name is sent to the room, therefore potentially used to save the file on the receiving machine; and on Windows extensions are still used to determine the opening application.
