### ISSUE TITLE
Crash in version 0.0.95.1

### ISSUE THREAD

**Issue by mymindstorm** [quotient-im/Quaternion#844]
A Fedora user filed a crash report for version 0.0.95.1 at https://bugzilla.redhat.com/show_bug.cgi?id=2071399 

A full backtrace and logs are attached to the RHBZ bug report.

It appears to be reproducible given that there are a few unique reports of this error, but it hasn't appeared in the last few months.

 - https://retrace.fedoraproject.org/faf/reports/371093/
 - https://retrace.fedoraproject.org/faf/reports/367394/

**Comment by KitsuneRal** [comment]
I remember having seen a dump like this myself at some point in another refactoring, and fixing it - but quite unfortunately I don't remember the context now, or where it was fixed. Quaternion 0.0.95.1 still uses the previous version of libQuotient (where the whole crash is due, actually) - so I'm tempted to just bind this issue to the next Quaternion release, and claiming it fixed thanks to using libQuotient 0.7.

**Comment by mymindstorm** [comment]
That works for me as well. I've recently updated the package to use commit 0315b395584b184cafef358aaf7ff309bc410583 for libQuotient .7

**Comment by KitsuneRal** [comment]
As agreed - marking this done as of 0.0.96 beta
