### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by philippludwig** [quotient-im/Quaternion#847]
### Description

If would be nice if the color/font of the text could be changed. Light gray on white is a bit hard to read:

![image](https://user-images.githubusercontent.com/3770792/216642684-143d4e1c-7c7a-45b6-8280-38a35f8902ec.png)

### Steps to reproduce

- Start, login, join a room

### Version information

- **Quaternion version**: v0.0.9.4
- **Qt version**: 5.15.2
- **Install method**: apt-get
- **Platform**: debian

**Comment by KitsuneRal** [comment]
Quaternion picks the foreground colour from the desktop theme. What is the WM/DE you are using?

**Comment by philippludwig** [comment]
I am using i3. Text is fine in all other Qt applications.

However, I stopped using Matrix now, so I don’t mind if you close this issue.

**Comment by KitsuneRal** [comment]
I don't close issues just because the poster is no more interested... Thanks for the feedback that it's fine in other Qt applications, that's valuable. I also understand you might not be available for more information, that's alright.

**Comment by ghost** [comment]
This works just fine in Haiku with the latest commit, so i don't see an issue.

I think the confusion here is that state messages are a bit more neutral gray and indeed have less contrast.

**Comment by KitsuneRal** [comment]
True. Guess I'll just switch to an italic font instead.
