### ISSUE TITLE
Impossible to select text, as display starts scrolling and doesn't clear previous selection

### ISSUE THREAD

**Issue by berrange** [quotient-im/Quaternion#857]
### Description

Someone posts a message into chat and I want to copy the text and paste it into another application. I can start highlighting the text I want to select, but if I have even the slightest vertical movement of the mouse, the selection will be terminated and the screen will start to scroll up/down.  Most of the time I can't even select more than a couple of words without having some slight vertical movement, let alone an entire line, or the entire message that spans multiple lines.

In addition the selection process seems to remember where you previously selected. So if you have a couiple of words selected and want to try again select the text, it starts the selection at where the previous incomplete selection ended, rather than where I've now clicked.

You can also end up having multiple messages selected, as it doesn't seem to clear the old selection on distinct chat messages.

### Steps to reproduce

- Attempt to highlight the text for a single chat message
- Any vertical movement of the mouse terminates the selection at the current pointer location and does vertical scrolling
- After a failed selection, attempt to select the text again, and it won't select from the mouse starting position, instead using end of the previous selection.

### Version information

- **Quaternion version**: quaternion-0.0.95.50~20230106g0315b395-1.fc37.x86_64
- **Qt version**: qt5-qtbase-5.15.8-6.fc37.x86_64
- **Install method**: Distro providqed RPM
- **Platform**: Fedora 37, GNOME shell desktop session

**Comment by KitsuneRal** [comment]
Should be fixed by #851; feel free to reopen if it still doesn't work.

**Comment by Tamaranch** [comment]
It's definitely better, however you can only select one line (one comment) at a time. But I guess that's a known limitation and another problem.

**Comment by KitsuneRal** [comment]
Yes, and yes...
