### ISSUE TITLE
Pre-connect chat history shows up as "unknown event" in E2EE rooms

### ISSUE THREAD

**Issue by chmeeedalf** [quotient-im/Quaternion#866]
### Description

It looks like Quaternion loads some history (join/leave events), but doesn't load chat events from encrypted rooms.  Looking at all the options, it appears past chat messages show up as "Unknown event", rather than chat.

### Steps to reproduce

- Join E2EE room from a device running Element (app.element.io)
- Send some messages, receive some.
- Join same room from Quaternion
- Under "View -> Display in Timeline" Select "Unknown events"

Past chats (before login) show up as "Unknown event", cannot be decrypted.  Right-clicking and "show detail" gives a clickable link to open in the browser, that I can then open with app.element.io.

### Version information

- **Quaternion version**: 0.0.96 beta (+git)
- **Qt version**: 5.15.8
- **Install method**: Compile from source
- **Platform**: Debian Bookworm, ppc64el

**Comment by KitsuneRal** [comment]
This is a consequence of not having https://github.com/quotient-im/libQuotient/issues/608 in place.
