### ISSUE TITLE
Pasting an image from a browser to the chat window crashes on send

### ISSUE THREAD

**Issue by chmeeedalf** [quotient-im/Quaternion#867]
### Description

Copy&Pasting an image from Firefox looks to paste something in the textbox, but upon sending Quaternion crashes with an assert failure: ASSERT: "!plainText.isEmpty() && !htmlText.isEmpty()" in file /.../client/chatroomwidget.cpp, line 428

### Steps to reproduce

- Copy an image, test from a web page
- Paste in Quaternion chat field
- Hit ENTER to send

Ideal behavior would be to convert the paste into an image upload, like Element does.  However, not crashing, or even just outright rejecting an image paste, would also work.

Adding some printf debugging to ChatEdit::insertFromMimeData(), I see the following:

hasHtml:  true  hasImage:  true 

html:  "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"><img class=\"avatar avatar-user\" src=\"https://avatars.githubusercontent.com/u/1408010?s=52&amp;v=4\" alt=\"@chmeeedalf\" width=\"26\" height=\"26\">"  -- end

"html: " and " -- end" being added by me as delimiters.

Quaternion dumps logs to the standard output. If you can find the logs and
identify any log snippets relevant to your issue, please include
those here (please be careful to remove any personal or private data):

ASSERT: "!plainText.isEmpty() && !htmlText.isEmpty()" in file /.../client/chatroomwidget.cpp, line 428

### Version information

- **Quaternion version**: 0.0.96-beta
- **Qt version**: 5.15.8
- **Install method**: Build from source (zip file download from GitHub) 
- **Platform**: Debian Bookworm, ppc64el

**Comment by chmeeedalf** [comment]
This as-is was fixed by PR #868, will open a different issue for image uploads.

**Comment by KitsuneRal** [comment]
Did you open that other issue? I don't seem to find it.

**Comment by chmeeedalf** [comment]
Yeah, it's issue #869.

**Comment by KitsuneRal** [comment]
Oh, thanks, this slipped through my fingers.
