### ISSUE TITLE
windows package with Chocolatey?

### ISSUE THREAD

**Issue by bish0polis** [quotient-im/Quaternion#885]
### Description

The Readme says

> Since there's no established package management on Windows to resolve dependencies

And I'm curious about our awareness of Chocolatey.org and its packaging ecosystem.

Packages are there; just, maybe not up to date.

### Steps to reproduce

1. choco install quaternion
1. rejoice

### Desired Result

- much rejoicing

### Observed Result

- very old package
- no joy

**Comment by KitsuneRal** [comment]
Oh yes, I'm well aware of it - I wouldn't quite call it established (despite its maturity) so if that line rubs you the wrong way feel free to submit a PR with better wording. As for the subject of the issue - unfortunately, the previous maintainer abandoned the package, and nobody including me never got to picking it up. Would you volunteer to do that? I was told it's not too hard; but I'm on Linux, can't maintain Windows stuff.

**Comment by bish0polis** [comment]
> Oh yes, I'm well aware of it 

Excellent!

> I wouldn't quite call it established (despite its maturity) so if that line rubs you the wrong way 

Seems the word 'established' is subjectively subjective.

All good.

**Comment by KitsuneRal** [comment]
Heh, so we don't get an updated Chocolatey package. Oh well.
