### ISSUE TITLE
MacOS download is missing code signature

### ISSUE THREAD

**Issue by suschizu** [quotient-im/Quaternion#894]
### Description

version 0.0.96 (https://github.com/quotient-im/Quaternion/releases/tag/0.0.96) isn't signed:
EXPECTED 'Aaron Raimist (VLEL2Z9Y59)'
FOUND ''

### Steps to reproduce

codesign -dv --verbose=4 /Path/To/Application.app

app cannot be opened in finder

### Version information

0.0.96 
Ventura (13.6)

<img width="751" alt="Screenshot 2024-01-13 at 18 53 16" src="https://github.com/quotient-im/Quaternion/assets/16004333/bd3adf0a-90cb-48e6-b791-12a24f855058">

**Comment by KitsuneRal** [comment]
@aaronraimist is it something you can help with? (I'm actually fine to direct everyone to use Homebrew instead, punting the signing problem on them...)

**Comment by aaronraimist** [comment]
Yeah I'll fix that this evening or tomorrow. Homebrew just downloads it from GitHub so it'll be fixed in both places.

**Comment by aaronraimist** [comment]
@suschizu version on GitHub releases has been signed. Homebrew PR should be merged shortly. Please test and let me know if it works for you now.

**Comment by suschizu** [comment]
great thanks for the quick fix - I can confirm that version 0.0.96 is now signed correctly again:

`Authority=Developer ID Application: Aaron Raimist (VLEL2Z9Y59)`
