### ISSUE TITLE
0.9.96 Windows package missing severall libs

### ISSUE THREAD

**Issue by ghost** [quotient-im/Quaternion#896]
Qt6quickcontrolls2.dll
Qt6QuickWidgets.dll
Qt6Sql.dll
libcrypto-3-x64.dll (probably openssl install this yourself)

**Comment by KitsuneRal** [comment]
libcrypto yes, it's install-yourself for now (maybe that would change soon-ish but not right now). The Qt parts missing is clearly a bug.

**Comment by KitsuneRal** [comment]
Are these actually the only libraries missing? I don't see Qt bundled at all...

**Comment by ghost** [comment]
It's not bundled indeed.

These are all that it gave me an error pop up for, it may very well be that those are "only" the direct dependencies and will pull in and complain for lower ones when provided.

**Comment by KitsuneRal** [comment]
Well, that shows the popularity of Quaternion on Windows... `windeployqt` failed during packaging so no Qt was bundled - and nobody noticed until now. Thanks for finding it, my most valuable tester.

**Comment by KitsuneRal** [comment]
Fixed in 4c53d18f.
