### ISSUE TITLE
Fails to build against latest libQuotient

### ISSUE THREAD

**Issue by chmeeedalf** [quotient-im/Quaternion#903]
### Description

Quaternion fails to build against latest libQuotient.  I see lots of errors such as:
/home/.../Quaternion/client/models/userlistmodel.cpp: In member function ‘virtual QVariant UserListModel::data(const QModelIndex&, int) const’:
/home/.../Quaternion/client/models/userlistmodel.cpp:83:33: error: no matching function for call to ‘Quotient::User::displayname(Quotient::Room* const&)’
   83 |         return user->displayname(m_currentRoom);
      |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /home/.../Quaternion/client/models/userlistmodel.cpp:23:
/usr/local/include/Quotient/user.h:66:13: note: candidate: ‘QString Quotient::User::displayname() const’
   66 |     QString displayname() const;
      |             ^~~~~~~~~~~

among many others.
### Steps to reproduce

Build from source against latest libQuotient (testing libQuotient 1cc0bd6cee).

### Version information

- **Quaternion version**: git (85997fbad)
- **Qt version**: 6.4.2 
- **Install method**: Source 
- **Platform**: Debian/ppc64le 

libQuotient 1cc0bd6cee

**Comment by KitsuneRal** [comment]
Quaternion 0.0.96 requires libQuotient 0.8 - this is written in [the BUILDING file](https://github.com/quotient-im/Quaternion/blob/dev/BUILDING.md). The commit you're referring to is from libQuotient's upcoming 0.9 version that breaks API/ABI compatibility as it [normally does between 0.x versions](https://github.com/quotient-im/libQuotient/blob/dev/README.md#apiabi-stability). Please use 0.8.2 tag or 0.8.x branch of Quotient to build Quaternion 0.0.96.
