### ISSUE TITLE
`Fonts\timeline_family` only affects usernames

### ISSUE THREAD

**Issue by al0fdf** [quotient-im/Quaternion#906]
### Description

When setting `Fonts\timeline_family` in the configuration file to `Noto Sans Emoji` so that I could see emoji reactions, I found that it only changed the font used for the usernames in the timeline, instead of the actual messages. In the readme, it states

> `Fonts/timeline_family` - font family (for example Monospace) to display messages in the timeline. If not specified, the application-wide font family is used.

Without Noto Color Emoji:
![image](https://github.com/user-attachments/assets/55564d40-d24a-440e-886f-ab66349494bb)

After applying Noto Color Emoji:
![image](https://github.com/user-attachments/assets/50b7a208-e1ba-4d35-a8ba-17854daf9a67)

### Version information

- **Quaternion version**: 

> Built from Git, commit SHA:
> `dc0381e379c957851079693c2d20e637f30e9445`
> Library commit SHA:
> `a313422d05818d241fc7f86087d250b184b26324`

- **Qt version**: 6.7.2
- **Install method**: git
- **Platform**: artix linux

**Comment by KitsuneRal** [comment]
I don't quite understand the captions for the two screenshots, have you typo'ed?
And looking at the room header, the change in font is quite apparent there as well. The timeline itself doesn't seem to actually change indeed, though.

**Comment by al0fdf** [comment]
> I don't quite understand the captions for the two screenshots, have you typo'ed? And looking at the room header, the change in font is quite apparent there as well. The timeline itself doesn't seem to actually change indeed, though.

I've corrected the typo.

What I meant is that the readme says that `timeline_family` sets the font used *to display messages in the timeline*. However, the only things that are updated with the font are the usernames and the room header, but not the message content itself. (as the blue dot character 🔵, still shows up as a square in both screenshots.)

**Comment by KitsuneRal** [comment]
Sorry for taking so long - indeed, it is a regression after migrating to Qt Quick Controls 2, a part of Qt 6. The fix is coming.
