### ISSUE TITLE
Sharing files and images doesn't work

### ISSUE THREAD

**Issue by artenax** [quotient-im/Quaternion#909]
Check this https://github.com/matrix-org/matrix.org/issues/2537

**Comment by KitsuneRal** [comment]
Quaternion is unfortunately lagging behind with releases. Support for authenticated media requests has been added in version 0.9 of libQuotient, the underpinning library, which will be released later this week; now that I'm more or less through with libQuotient, I'll update the Quaternion repo to use it. Expect Quaternion-from-git to start working again in the nearest days.

**Comment by KitsuneRal** [comment]
Should be fixed by #910.

**Comment by artenax** [comment]
I compiled the latest git's libQuotient + Quaternion (Qt6) in Mageia Cauldron (Docker) and can confirm it works (accepting files), no more 404 error.
