### ISSUE TITLE
"Invalid access token passed." on every restart

### ISSUE THREAD

**Issue by dblsaiko** [quotient-im/Quaternion#917]
### Description

When closing and re-opening Quaternion, the server says the access token is invalid every time.

This does not happen with NeoChat which also uses libQuotient, so I assume it's a bug in Quaternion.

### Steps to reproduce

- Log in, both E2EE and "Stay logged in" checked
- Close and re-open Quaternion

An "invalid access token passed" dialog appears.

```
quaternion.main: Using application font: "IBM Plex Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
qt.qpa.wayland: eglSwapBuffers failed with 0x300d, surface: 0x0
quotient.main: Keychain request: app "quaternion" id "@2xsaiko:tchncs.de-Pickle"
quotient.e2ee: The fixed buffer source is shared; assuming that the caller is responsible for securely clearing other copies
quotient.main: E2EE switched on in "!AyxWvxsNFsvTTMqxgA:matrix.org"
quotient.main: E2EE switched on in "!BHRiZCNBKpCRDyiJaU:matrix.org"
quotient.main: E2EE switched on in "!BzvTLOXlOQtnacSBeN:matrix.org"
quotient.main: E2EE switched on in "!CasLwbcKjuJMMbuUyt:matrix.org"
quotient.main: E2EE switched on in "!GbDcwwIbcoeUMDCClS:envs.net"
quotient.main: E2EE switched on in "!KjDhWikYChYIWTmuCe:nani.wtf"
quotient.main: E2EE switched on in "!VNVXbWEPpIiJuUaTvZ:mozilla.org"
quotient.main: E2EE switched on in "!YnzFmVqKlfGItwkHjO:matrix.org"
quotient.main: E2EE switched on in "!jADFIpUETnxNTgnhDQ:computational.beauty"
quotient.main: E2EE switched on in "!lmoIPcCgIXstvPQKim:matrix.org"
quotient.main: E2EE switched on in "!mfDqUXnBhumdcRcHmB:matrix.org"
quotient.main: E2EE switched on in "!vudZySJbCmIWLwcTnc:necauq.ua"
quotient.jobs: 401 <- GET https://matrix.tchncs.de/_matrix/client/versions
quotient.jobs: "GetVersionsJob" status Unauthorised: Invalid access token passed.
quotient.jobs: 401 <- GET https://matrix.tchncs.de/_matrix/client/v3/capabilities
quotient.jobs: "GetCapabilitiesJob" status Unauthorised: Invalid access token passed.
quotient.jobs: 401 <- GET https://matrix.tchncs.de/_matrix/client/v3/account/whoami
quotient.jobs: "GetTokenOwnerJob" status Unauthorised: Invalid access token passed.
```

The "invalid access token passed" dialog says:

> Request URL: https://matrix.tchncs.de/_matrix/client/v3/account/whoami
Response:
{"errcode":"M_UNKNOWN_TOKEN","error":"Invalid access token passed.","soft_logout":false}

### Version information

- **Quaternion version**: 54fc44d1a52ced20adb39023877716abaa399b05, https://github.com/quotient-im/libQuotient/commit/e70e242a9b436532bc57569a76e57330cad53896
- **Qt version**: 6.7.3
- **Install method**: Compiled from source
- **Platform**: Gentoo Linux ~amd64, system compiler is clang, C++ STL is libc++

**Comment by KitsuneRal** [comment]
Do NeoChat and Quaternion use the same commit of libQuotient? If not, the fix might be in https://github.com/quotient-im/libQuotient/pull/827 that will be in libQuotient 0.9.1 coming real-soon-now (a week maybe).

**Comment by dblsaiko** [comment]
Yes, I've both compiled it against the submodule and the system package libQuotient (0.9.0) which NeoChat also uses.

However, that patch does fix it, thanks!
