### ISSUE TITLE
Quaternion fails to compile with -DCMAKE_DISABLE_PRECOMPILE_HEADERS=YES

### ISSUE THREAD

**Issue by dblsaiko** [quotient-im/Quaternion#918]
### Description

Compiling Quaternion with -DCMAKE_DISABLE_PRECOMPILE_HEADERS=YES makes it fail to compile:

```
In file included from /Users/saiko/Src/tmp/Quaternion/client/networkconfigdialog.cpp:7:
In file included from /Users/saiko/Src/tmp/Quaternion/client/networkconfigdialog.h:9:
In file included from /Users/saiko/Src/tmp/Quaternion/client/dialog.h:9:
In file included from /usr/include/qt6/QtCore/QFlags:1:
In file included from /usr/include/qt6/QtCore/qflags.h:7:
/usr/include/qt6/QtCore/qcompare_impl.h:26:49: error: no member named 'is_null_pointer_v' in namespace 'std'
   26 |     template <typename T, std::enable_if_t<std::is_null_pointer_v<T>, bool> = true>
      |                                            ~~~~~^
/usr/include/qt6/QtCore/qcompare_impl.h:26:67: error: 'T' does not refer to a value
   26 |     template <typename T, std::enable_if_t<std::is_null_pointer_v<T>, bool> = true>
      |                                                                   ^
/usr/include/qt6/QtCore/qcompare_impl.h:26:24: note: declared here
   26 |     template <typename T, std::enable_if_t<std::is_null_pointer_v<T>, bool> = true>
      |                        ^
/usr/include/qt6/QtCore/qcompare_impl.h:26:77: error: expected member name or ';' after declaration specifiers
   26 |     template <typename T, std::enable_if_t<std::is_null_pointer_v<T>, bool> = true>
      |                                                                             ^
```

I noticed because I was making a Gentoo package for it, and Gentoo's CMake build handler sets this option.

Patch here: [0001-Include-type_traits-to-fix-error-when-compiling-with.patch](https://git.sr.ht/~dblsaiko/ebuilds/tree/master/item/net-im/quaternion/files/0001-Include-type_traits-to-fix-error-when-compiling-with.patch)

### Steps to reproduce

- cmake -B build -DCMAKE_DISABLE_PRECOMPILE_HEADERS=YES
- make -C build

### Version information

- **Quaternion version**: 54fc44d1a52ced20adb39023877716abaa399b05, https://github.com/quotient-im/libQuotient/commit/e70e242a9b436532bc57569a76e57330cad53896
- **Qt version**: 6.7.3
- **Install method**: Compiled from source
- **Platform**: Gentoo Linux ~amd64, system compiler is clang, C++ STL is libc++

**Comment by KitsuneRal** [comment]
Good find, thanks for spotting.

**Comment by KitsuneRal** [comment]
Looking closer at the place where the error occurrs, I think it's actually a problem with Qt. If `std::is_null_pointer_v` is used in `qcompare_impl.h`, surely that file must include `<type_traits>`? I suggest filing an issue at https://bugreports.qt.io about this.
