### ISSUE TITLE
error: thumbnailprovider.h: No such file or directory

### ISSUE THREAD

**Issue by xiota** [quotient-im/Quaternion#919]
Trying to build 54958f3.

```
client/timelinewidget.cpp:6:10: fatal error: thumbnailprovider.h: No such file or directory
```

Was supposed to be removed?

https://github.com/quotient-im/Quaternion/blob/54958f32ce37ffd9428b1bc7203dfa39b75b8170/client/timelinewidget.cpp#L6

**Comment by KitsuneRal** [comment]
Yes, pushed too soon accidentally. The guardrails on this project are still much weaker than on libQuotient...

**Comment by KitsuneRal** [comment]
Fixed as of the current `dev`.
